name: Test the book

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the book
        run: |
          cd book && jupyter book build --execute --html
